node {
   stage('Preparation') {
      git 'https://github.com/Bliblob/chess4you_java.git'
   }
   stage('CleanNBuild') {
      if (isUnix()) {
         sh "cd /chess4you_java/"
         sh "gradlew clean"
         sh "gradlew build"
      } else {
         bat("cd /chess4you_java/")
         bat("gradlew clean")
         bat("gradlew build")
      }
   }
   stage('RunCodeCoverage') {
      if (isUnix()) {
         sh "gradlew jacoco"
      } else {
         bat("gradlew jacoco")
      }
   }
   stage('RunSonarScanner') {
		bat("call /scripts/runSonarScanner")
   }
   stage('DeployToTomcat') {
      if (isUnix()) {
         sh "gradlew war"
      } else {
         bat("gradlew war")
         bat("copy 'C:\git\chess4you_java\chess4you_java\build\libs\chess4you-1.0-SNAPSHOT.war' ''")
      }
   }
}